### ISSUE TITLE
未去除换行符导致在windows下加载不到任何ip 

### ISSUE THREAD

**Issue by zhaohonggangnj** [BruceWind/CloudFrontIPSelector#2]
![image](https://github.com/BruceWind/CloudFrontIPSelector/assets/57297486/09427365-de5e-40ba-98fa-6aa4034ab47d)
![image](https://github.com/BruceWind/CloudFrontIPSelector/assets/57297486/989155f1-1b0d-47ea-9bd5-1c56e8e1f1d3)

**Comment by BruceWind** [comment]
Thanks a lot.

**Comment by BruceWind** [comment]
related to https://github.com/BruceWind/CloudFrontIPSelector/pull/3

**Comment by BruceWind** [comment]
This pull request merged.
